hoomd:
  - v2
  - v3
  - v4
  - v5
  - v6
  - v7

python:
  - 3.10.* *_cpython
  - 3.11.* *_cpython

is_python_min:
  - true
  - false

pybind11_abi:
  - 4
  - 4
  - 4
  - 11
  - 11
  - 11

zip_keys:
  -
    - python
    - is_python_min
  -
    - hoomd
    - pybind11_abi
